#!/bin/sh

set -e

SCRIPT_PATH=$(dirname $(readlink -f $0))
. $SCRIPT_PATH/post-receive-utils.sh

title 'push: git-bare: post receive hook'
deploy

if [ "$DOCKERIZE" = "true" ]; then
	dockerize
else
	restart_application
fi

post_startup
