#!/bin/sh

PROJECT_ENVIRONMENT=default
SERVICE_NAME=app-name
GIT_BARE_REPO=$HOME/repos/$SERVICE_NAME/$PROJECT_ENVIRONMENT.git
DEPLOY_DIR=$HOME/sites/$SERVICE_NAME/$PROJECT_ENVIRONMENT
WORK_TREE=$DEPLOY_DIR/$(date +%s)

if [ ! -d $DEPLOY_DIR ]; then
        echo "Creating $DEPLOY_DIR"
        mkdir $DEPLOY_DIR
fi
echo "Creating working directory $WORK_TREE"
mkdir $WORK_TREE

echo "Checking out working copy"
git --work-tree=$WORK_TREE --git-dir=$GIT_BARE_REPO checkout -f
echo "Updating current symlink to $WORK_TREE"
rm $DEPLOY_DIR/current
cd $DEPLOY_DIR && ln -sf $WORK_TREE current

echo "Restarting application"
cd $DEPLOY_DIR/current && PROJECT_ENVIRONMENT=$PROJECT_ENVIRONMENT sh ./deploy/run.sh stop && PROJECT_ENVIRONMENT=$PROJECT_ENVIRONMENT sh ./deploy/run.sh start
