#!/bin/bash -l

PROJECT_ENVIRONMENT=demo
SERVICE_NAME=rails-onboarding-demo
GIT_BARE_REPO=$HOME/repos/$SERVICE_NAME/$PROJECT_ENVIRONMENT.git
DEPLOY_DIR=$HOME/sites/$SERVICE_NAME/$PROJECT_ENVIRONMENT
WORK_TREE=$DEPLOY_DIR/releases/$(date +%s)

if [ ! -d $DEPLOY_DIR ]; then
        echo "Creating $DEPLOY_DIR"
        mkdir $DEPLOY_DIR
fi
echo "Creating working directory $WORK_TREE"
mkdir -p $WORK_TREE

echo "Checking out working copy"
git --work-tree=$WORK_TREE --git-dir=$GIT_BARE_REPO checkout -f
echo "Updating current symlink to $WORK_TREE"
rm $DEPLOY_DIR/current
cd $DEPLOY_DIR && ln -sf $WORK_TREE current
#rm $SERVICE_NAME.pid
#ln -s /tmp/$SERVICE_NAME.pid $SERVICE_NAME.pid

source $HOME/.bashrc
source /etc/profile
cd $DEPLOY_DIR/current && /home/deploy/.rbenv/bin/rbenv exec bundle install 
echo "Restarting application"
cd $DEPLOY_DIR/current && sh ./config/deploy/run.sh stop && sh ./config/deploy/run.sh start
