#!/bin/sh

set -e

SCRIPT_PATH=$(dirname $(readlink -f $0))
. $SCRIPT_PATH/post-receive-utils.sh

deploy

if [ "$FORMAT" = "nextjs" ] && [ "$BUILD" = "" ]; then
	title 'deploy - build'
	cd $DEPLOY_DIR/current
	npm install
  npx next build
	npx next export
fi

post_startup
