#!/bin/sh

set -e

SCRIPT_PATH=$(dirname $(readlink -f $0))
. $SCRIPT_PATH/post-receive-utils.sh

title 'post-push: docker-pull: post receive hook'
deploy

REGISTRY_IMAGES=$(grep 'image:' $DEPLOY_DIR/current/docker-compose.yml | sed 's/image://g')
IMAGE_LIST=$(echo "$REGISTRY_IMAGES" | cut -d";" -f1)
for n in $IMAGE_LIST; do
	docker pull $n
done

if [ $SAVE_LOG = true ]; then
	CURRENT_LOG_FOLDER="$DEPLOY_DIR/shared/logs"
	mkdir -p "$CURRENT_LOG_FOLDER"
	cd $DEPLOY_DIR/current && docker-compose -f docker-compose.yml up --no-build 2>&1 | tee -a "$CURRENT_LOG_FOLDER/$SERVICE_NAME.log" &
else
	cd $DEPLOY_DIR/current && docker-compose -f docker-compose.yml up -d --no-build
fi

post_startup
