#!/bin/sh

set -e

SCRIPT_PATH=$(dirname $(readlink -f $0))
. $SCRIPT_PATH/post-receive-utils.sh

deploy

title 'starting application'
echo "Restarting application"
cd $DEPLOY_DIR/current && sh ./deploy/run.sh stop && sh ./deploy/run.sh start

post_startup
