#!/bin/sh

set -e

if [ -f "$HOME/.profile" ]; then
	. "$HOME/.profile"
fi

SCRIPT_PATH=$(dirname $(readlink -f $0))
. $SCRIPT_PATH/post-receive-utils.sh

deploy

if [ "$FORMAT" = "reactjs" ] && [ "$BUILD" = "" ]; then
	title 'deploy - build'
	cd $DEPLOY_DIR/current
	npm install
	npm run build

	restart_application
fi

post_startup
