#!/bin/bash -l

SCRIPT_PATH=$(dirname $(readlink -f $0))
. $SCRIPT_PATH/config.sh
. $SCRIPT_PATH/post-receive-utils.sh

GIT_BARE_REPO=$HOME/repos/$SERVICE_NAME/$PROJECT_ENVIRONMENT.git
DEPLOY_DIR=$HOME/sites/$SERVICE_NAME/$PROJECT_ENVIRONMENT
WORK_TREE=$DEPLOY_DIR/releases/$(date +%s)

if [ ! -d $DEPLOY_DIR ]; then
        echo "Creating $DEPLOY_DIR"
        mkdir -p $DEPLOY_DIR
fi
echo "Creating working directory $WORK_TREE"
mkdir -p $WORK_TREE

echo "Checking out working copy"
git --work-tree=$WORK_TREE --git-dir=$GIT_BARE_REPO checkout -f
echo "Updating current symlink to $WORK_TREE"
rm $DEPLOY_DIR/current
cd $DEPLOY_DIR && ln -sf $WORK_TREE current

# create shared resources links
create_symlinks

source $HOME/.bashrc
source /etc/profile
cd $DEPLOY_DIR/current
$HOME/.rbenv/bin/rbenv exec bundle check || $HOME/.rbenv/bin/rbenv exec bundle install
if [ "$PRECOMPILE_ASSETS" != "false" ]; then
	$HOME/.rbenv/bin/rbenv exec bundle exec rake assets:precompile
fi
if [ "$ACTIVE_RECORD" != "false" ]; then
	$HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
fi
echo "Restarting application"
cd $DEPLOY_DIR/current && sh ./config/deploy/run.sh stop && sh ./config/deploy/run.sh start
