#!/bin/sh

SCRIPT_PATH=$(dirname $(readlink -f $0))
. $SCRIPT_PATH/config.sh
. $SCRIPT_PATH/post-receive-utils.sh
. $SCRIPT_PATH/util.sh

title 'deploy - post receive hook'

GIT_BARE_REPO=$HOME/repos/$SERVICE_NAME/$PROJECT_ENVIRONMENT.git
DEPLOY_DIR=$HOME/sites/$SERVICE_NAME/$PROJECT_ENVIRONMENT
WORK_TREE=$DEPLOY_DIR/releases/$(date +%s)

if [ ! -d $DEPLOY_DIR ]; then
        echo "Creating $DEPLOY_DIR"
        mkdir -p $DEPLOY_DIR
fi
echo "Creating working directory $WORK_TREE"
mkdir -p $WORK_TREE

echo "Checking out working copy"
git --work-tree=$WORK_TREE --git-dir=$GIT_BARE_REPO checkout -f 2>&1 | indent
echo "Updating current symlink to $WORK_TREE"
rm $DEPLOY_DIR/current
cd $DEPLOY_DIR && ln -sf $WORK_TREE current
mkdir -p $DEPLOY_DIR/current/logs

# create shared resources links
create_symlinks

title 'deploy - build'
cd $DEPLOY_DIR/current
npm install
npm run build
