#!/bin/bash -l

set -e

SCRIPT_PATH=$(dirname $(readlink -f $0))
. $SCRIPT_PATH/post-receive-utils.sh

deploy

source $HOME/.bashrc
source /etc/profile
cd $DEPLOY_DIR/current

title 'deploy - bundle install'
$HOME/.rbenv/bin/rbenv exec bundle check || $HOME/.rbenv/bin/rbenv exec bundle install --path vendor/bundle --jobs 4 --without development test --deployment --quiet 2>&1 | indent
if [ "$PRECOMPILE_ASSETS" != "false" ]; then
	title 'deploy - precompile assets'
	$HOME/.rbenv/bin/rbenv exec bundle exec rake assets:precompile 2>&1 | indent
fi

if [ "$ACTIVE_RECORD" != "false" ]; then
	title 'deploy - migrations'
	$HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate 2>&1 | indent
fi

title 'start application'
echo "Restarting application"
cd $DEPLOY_DIR/current && sh ./config/deploy/run.sh stop && sh ./config/deploy/run.sh start
