# default SSH port
DEPLOYMENT_SERVER_PORT=22
DEPLOYMENT_SERVER_PROTOCOL=ssh
DEPLOYMENT_SERVER_USER=deploy
REPO_TYPE=git
PUSH=git-bare
PACKAGE=git
RESTART_COMMAND="sh deploy/run.sh restart"
DEPLOYMENT_DIR='$HOME/sites'
DOCKER_COMPOSE_OPTS="--no-cache"
