# default SSH port
DEPLOYMENT_SERVER_PORT=22
DEPLOYMENT_SERVER_PROTOCOL=ssh
DEPLOYMENT_SERVER_USER=deploy
REPO_TYPE=git
PUSH=git-bare
PACKAGE=git
RESTART_COMMAND="sh deploy/run.sh restart"
DEPLOYMENT_DIR='$HOME/sites'
DOCKER_COMPOSE_OPTS=""
KUBERNETES_CRED="fincred"
DOCKER_REGISTRY=https://dockerhub.finology.com.my
KUBERNETES_HOME="$HOME/.kube"
KUBERNETES_CLUSTER="dev"
KUBERNETES_NGINX="true"
KUBERNETES_REPLICAS="1"
KUBERNETES_CERT_MANAGER="letsencrypt-staging"
